<?php

function drupalika_mail_module_menu() {
  $items = array();
  
  $items['drupalika/develop'] = array(
    'title' => 'Developing a new module',
    'page callback' => 'drupalika_develop_page',
    'access callback' => TRUE,
  );
  
  return $items;
}

function drupalika_develop_page() {
  $module = 'drupalika_mail_module';
  $key = 'email';
  $to = "info@drupalika.org";
  $from = variable_get('site_mail', 'drupalika@gmail.com');
  global $user;
  $params = array(
	'name' => $user->name,
  );
  $language = language_default();
  $send = TRUE;
  $result = drupal_mail($module, $key, $to, $language, $params, $from, $send);
  if ($result['result'] == TRUE) {
    drupal_set_message(t('Your message has been sent.'));
  }
  else {
    drupal_set_message(t('Some problems have occurred.'), 'error');
  };

  return "This is the content of drupalika/develop page.";
}

function drupalika_mail_module_mail($key, &$message, $params) {
	$message['subject'] = "Subject of email";
	$message['body'][] = t('@name sent you the following message:', array('@name' => $params['name']));
}